version: "3"
services:
  nestjs:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - DATABASE_NAME=viact
    depend-ons:
      - mysql
  mysql:
    image: mysql:8.3.0
    environment:
      - DATABASE_HOST=172.17.0.2
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - DATABASE_NAME=viact
    ports:
      - 3306:3306
